server:
  port: 7001

spring:
  application:
    name: eureka-client-a

eureka:
  client:
    service-url:  # Eureka 服务端和客户端的交互地址, 集群用逗号隔开
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true  # 注册自己
    fetch-registry: true  # 拉取服务列表
    registry-fetch-interval-seconds: 5  # 表示 Eureka Client 间隔多久去拉取服务注册信息
  instance:
    hostname: localhost # 服务主机名称
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}  # 实例 ID
    prefer-ip-address: true   # 服务列表以 ip 的形式展示
    lease-renewal-interval-in-seconds: 10   # 表示 eureka client 发送心跳给 server 端的频率
    lease-expiration-duration-in-seconds: 20 # 表示 Eureka Server 至上一次收到的 Client 心跳之后, 等待下一次心跳的超时时间, 在这个时间内若没收到下一次心跳, 则移除该实例